name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Compile Java files
      run: javac -d out $(find src/main/java -name "*.java")

    - name: Run Tests
      run: java -cp out org.junit.runner.JUnitCore $(find src/test/java -name "*.java" | sed 's/src\/test\/java\///' | sed 's/\.java//' | tr '/' '.')
